spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lianfei1/config-test2
          search-paths: config
          username: 597657148@qq.com
          password: xr150806
          basedir: E:\springboot\spring_cloud\git-repo
  application:
    name: config-server
  rabbitmq:
    host: localhost
    port: 5672
    username: config-server
    password: 123456

#  security:
#    user:
#      name: hello
#      password: 123456


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://node1:10097/eureka/
server:
  port: 7000

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true